Looking at how an encoding, error, error detection, correction and decoding procedure would look like when done manually

Import first

In [84]:
from numpy import *
import cmath
from random import randrange

Set variables

In [57]:
theta = pi/4
a = cos(theta)
b = sin(theta)

In [58]:
one = array([[int(0)], [int(1)]])
zero = array([[int(1)], [int(0)]])
psi = a*zero + b*one

In [59]:
psi

array([[0.70710678],
       [0.70710678]])

Define matrices

In [128]:
X = array([[0 , 1], [1, 0]])
Iden = array([[1 , 0], [0, 1]])
Z = array([[1,0],[0, -1]])
CNOT = array([[1 , 0 , 0 , 0], [0 , 1 , 0 , 0], [0 , 0 , 0 , 1], [0 , 0 , 1 , 0]])

Tensor Products (bit flips)

In [129]:
X1 = kron(kron(X, Iden), Iden)

In [130]:
X2 = kron(kron(Iden, X), Iden)

In [131]:
X3 = kron(kron(Iden, Iden), X)

Measurements

In [132]:
Z1 = kron(kron(Z, Z), Iden)
Z2 = kron(kron(Iden, Z), Z)

Encoding

In [163]:
psi3 = kron((kron(psi,zero)), zero)
psi3

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ]])

In [134]:
CNOT13 = array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])

In [135]:
CNOT12 = array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0]])

In [142]:
enc = CNOT12.dot(psi3)
enc

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ]])

In [143]:
psie = CNOT13.dot(enc)
psie

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678]])

In [47]:
psip = kron((kron(one,one)),one) + kron((kron(zero,zero)),zero)

Random bit flips

In [149]:
k = randrange(4)
print(k)

0


In [150]:
if k == 0:
    psir = X1.dot(psie)
elif k == 1:
    psir = X2.dot(psie)
elif k == 2:
    psir = X3.dot(psie)
elif k == 3:
    psir = psie

In [151]:
psir

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ]])

Syndrome

In [152]:
if int(transpose((Z1.dot(psir))).dot(psir))==1:
    val1 = 0
elif int(transpose((Z1.dot(psir))).dot(psir))== -1:
    val1 = 1

In [153]:
if int(transpose((Z2.dot(psir))).dot(psir))==1:
    val2 = 0
elif int(transpose((Z2.dot(psir))).dot(psir))== -1:
    val2 = 1

In [155]:
if (val1 == 0) & (val2 == 0):
    print("No error")
    err = 0
elif (val1 == 0) & (val2 == 1):
    print("Qubit 3 has flipped")
    err = 3
elif (val1 == 1) & (val2 == 1):
    print("Qubit 2 has flipped")
    err = 2
elif (val1 == 1) & (val2 == 0):
    print("Qubit 1 has flipped")
    err = 1

Qubit 1 has flipped


Correction

In [161]:
if err == 1:
    psif = (X1.dot(psir))
elif err == 2:
    psif = X2.dot(psir)
elif err == 3:
    psif = (X3.dot(psir))
elif err == 0:
    psif = psir

In [162]:
psif

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678]])

Decoding

In [1]:
CNOT12.dot(CNOT13.dot(psif))

NameError: name 'CNOT12' is not defined