Playing with the idea of using deep neural net - not used in project

In [1]:
from numpy import *
import cmath
from random import randrange
import pandas as pd
import time
from IPython.display import clear_output

In [2]:
a = 0.5
b = 0.5
one = array([[int(0)], [int(1)]])
zero = array([[int(1)], [int(0)]])
psi1 = (1/(sqrt(2)))*(zero + one)
psi1

array([[0.70710678],
       [0.70710678]])

In [3]:
X = array([[0 , 1], [1, 0]])
Z = array([[1,0],[0,-1]])
Iden = array([[1 , 0], [0, 1]])
Y = array([[0 , -1j], [1j, 0]])
H = (1/(sqrt(2)))*array([[1 , 1], [1, -1]])
S = array([[1 , 0], [0, 1j]])

In [4]:
right = Y.dot(Z.dot(X.dot(zero)))
right

array([[0.+1.j],
       [0.+0.j]])

In [5]:
list2 = [Iden, X, Y, Z, H, S]
list1 = [zero, one, psi1]

In [6]:
def probability(guess, right):
    summ = 0
    for i in range(0,2):
        diff = (guess[i] - right[i])
        summ+= abs(diff)
    score = 1 - (summ)/2
    return(float(score))

In [16]:
W1 = random.rand(6,2)
W2 = random.rand(6,6)

In [33]:
H.dot(one)

array([[ 0.70710678],
       [-0.70710678]])

In [52]:
x = zero

In [75]:
for z in range(0,20):
    x = zero
    print(z)
    flag = 0
    pen = 0
    reward = 0
    for t in range(0,7):
        pen =+ 0.2
    
        h = dot(W1, x) # compute hidden layer neuron activations
        sigh = 1.0 / (1.0 + exp(-h))#sigmoid
        logp = dot(W2, sigh) # compute log probability of going up
        p = 1.0 / (1.0 + exp(-logp))
        ind = argmax(p) #Next action
        psinew = (list2[ind]).dot(x) # New state
        x = psinew.copy()
        print(ind)
        if probability(x, right) == 1:
            print('goal reached')
            flag = 1
            reward += pen + flag
            break
        reward += pen
    if flag == 0:
        print('not reached')
        W1 = random.rand(6,2)
        W2 = random.rand(6,6)
    else:
        break

    

0
2
1
goal reached


In [59]:
W2

array([[0.83060673, 0.83049942, 0.28502113, 0.72098885, 0.19026584,
        0.19344432],
       [0.45554775, 0.69618351, 0.87650431, 0.70624459, 0.26994246,
        0.6209189 ],
       [0.67939143, 0.87295226, 0.9607009 , 0.12070636, 0.89819894,
        0.03535975],
       [0.05138235, 0.38950437, 0.34051004, 0.02667427, 0.84785546,
        0.03807095],
       [0.87224289, 0.7287939 , 0.14125261, 0.86743017, 0.05760465,
        0.55129598],
       [0.09860364, 0.29137393, 0.8163821 , 0.45035831, 0.10234742,
        0.49648135]])

In [71]:
x = psi1
h = dot(W1, x) # compute hidden layer neuron activations
sigh = 1.0 / (1.0 + exp(-h))#sigmoid
logp = dot(W2, sigh) # compute log probability of going up
p = 1.0 / (1.0 + exp(-logp))

In [72]:
p

array([[0.89403608],
       [0.92259947],
       [0.92717397],
       [0.76268858],
       [0.89960331],
       [0.82183832]])

In [70]:
h

array([[1.14007172],
       [0.92260359],
       [1.0803706 ],
       [0.57882135],
       [0.64986582],
       [0.26000648]])