In [1]:
from numpy import *
import cmath
from random import randrange
import pandas as pd
import time
from IPython.display import clear_output
import scipy
import matplotlib.pyplot as plt

In [120]:
one = array([[int(0) + 0j], [int(1) + 0j]])
zero = array([[int(1) + 0j], [int(0) + 0j]])
plus = (1/sqrt(2))*(zero + one)
minus = (1/sqrt(2))*(zero - one)
psi = (sqrt(1 - (1/6)**2))*one + (1/6)*zero
psi

array([[0.16666667+0.j],
       [0.9860133 +0.j]])

In [3]:
def norm(state):
    prod = scipy.sqrt(transpose(state.conjugate()).dot(state))
    return(asscalar(prod))

In [4]:
def fidelityp(guess, right):
    mult = (transpose(guess.conjugate())).dot(right)*(transpose(right.conjugate())).dot(guess)
    #print(mult)
    root = asscalar((mult))
    return(abs(root))

In [6]:
H = (1/sqrt(2))*array([[1,1],[1, -1]])
I = array([[1 , 0], [0, 1]])
T = array([[1, 0], [0, exp((1j*pi)/4)]])
S = array([[1, 0], [0, 1j]])

In [7]:
CNOT12 = array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
CNOT21 = array([[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0]])
H1 = kron(H,I)
H2 = kron(I,H)
T1 = kron(T,I)
T2 = kron(I,T)
I2 = kron(I,I)
S1 = kron(S,I)
S2 = kron(I,S)

In [22]:
X = array([[0 , 1], [1,0]])
X1 = kron(X , I)
X2 = kron(I,X)

In [8]:
glist = [I2, CNOT12, CNOT21, H1, H2, T1, T2, S1, S2]

In [121]:
zero2 = kron(zero,zero)
one2 = kron(one,one)
zeroone = kron(zero,one)
onezero = kron(one,zero)
psizero = kron(psi,zero)
psizero

array([[0.16666667+0.j],
       [0.        +0.j],
       [0.9860133 +0.j],
       [0.        +0.j]])

In [68]:
Q_table = pd.DataFrame()
for m in range(0,len(glist)):
    gate = m
    new = (glist[m].dot(zero2))
    Q = pd.DataFrame({'state' : str(zero2), 'gate':gate, 'new': str(new), 'Q':0, 'fidelity':0}, index=[0])
    Q_table = Q_table.append(Q)
Q_table = Q_table.reset_index(drop=True)

In [69]:
Q_table

state  gate  \
0  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     0   
1  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     1   
2  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     2   
3  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     3   
4  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     4   
5  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     5   
6  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     6   
7  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     7   
8  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     8   

                                                 new  Q  fidelity  
0        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0  
1        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0  
2        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0  
3  [[0.70710678+0.j]\n [0.        +0.j]\n [0.7071...  0         0  
4  [[0.70710678+0.j]\n [0.70710678+0.j]\n [0.    ...  0         0  
5        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0  
6        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0  
7        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0  
8        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]  0         0

In [70]:
alpha = 0.5 #how much we update Q for every new action
gamma = 0.9 #discount factor 

num_iter = 1 #how many agents will come up with their own Q values from scratch
num_repeats = 350 #How many events one agent will go through to obtain Q values
penalty = 0.1 #How much taken off reward for each step
steps = 10 #How many steps in an event

In [71]:
right = X1.dot(zero2)
right

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j]])

In [129]:
final = pd.DataFrame() #Dataframe to store state action pairs for top Q values for each agent
tots1 = pd.DataFrame() #Dataframe to store all Q values of all agents 
for iter in range(0,num_iter): #Begin an agent
    table = together.copy() #set the starting dataframe (empty Q values or precalculated)
    print(str(iter) + ' has begun')
    for repeats in range(0,num_repeats):
        psinit = zero2.copy()
        psiold = psinit.copy()
        #save the current state
        reward = 0 #Reset the reward
        for t in range(0,steps): #begin a step
            reward += penalty #add more penalty with each step
        
            sec = table[table['state']==str(psiold)] #choose rows of the original table that contain the current state
            
            if len(sec) == 0: #if the new state is not in the dataframe, insert it with all the possible actions
                for s in range(0,len(glist)):
                    lad = glist[s].dot(psiold)
                    sec = pd.DataFrame({'state' : str(psiold), 'gate':s, 'new':str(lad), 'Q':0, 'fidelity':0}, index=[0])
                    table = table.append(sec)
        
            gather = pd.DataFrame() #dataframe to collect all possible new states 
            for n in range(0,(len(sec))): #iterate through the rows that contain the current state
                for z in range(0,len(glist)): # find the action associated with the state in each row
                    if(sec.iloc[n]['gate']== z):
                        apply = array(glist[z])
                        zed = z
                    
                psinew = apply.dot(psiold) #create new state by applying action
                
                
                news = table[table['state']==str(psinew)] #choose part of dataframe that contains the new state
            
                if len(news) == 0: #if the new state is not in the dataframe, insert it with all the possible actions
                    for s in range(0,len(glist)):
                        lad = glist[s].dot(psinew)
                        news = pd.DataFrame({'state' : str(psinew), 'gate':s, 'new':str(lad), 'Q':0, 'fidelity':0}, index=[0])
                        table = table.append(news)
                    
                maxQ = max(news['Q']) #find the max Q value the new state
                gather = gather.append(news).drop_duplicates() #create a dataframe of all possible new states
                plus = 0 #reset award
                if (fidelityp(psiold, right)) > 0.99999999999:
                     plus = 5
                elif (fidelityp(psiold, right)) > 0.85:
                     plus = (fidelityp(psiold, right))*(4/(0.15)) + (1 - (fidelityp(psiold, right))*(4/(0.15)))
                else:
                    plus = 0    
                table.loc[(table.state == str(psiold)) & (table.gate == zed), 'Q'] += alpha*((plus - reward) + gamma*(maxQ) - sec.iloc[n]['Q'])
                table.loc[(table.state == str(psiold)) & (table.gate == zed), 'fidelity'] = (fidelityp(psiold, right))
                #update the Q value of the old state based on the rewards given by the new state
            if plus == 5: #If we have reached the state we want we can stop
                print('goal reached')
                break
            else:
                top = gather.loc[(gather.Q == max(gather['Q']))] #collect the max Q value from all possible new states
                toparray =[] #sort these into an array with their associated action
                actarray =[]
                for o in range(0,len(top)):
                    for p in range(0,len(glist)):
                        if (str((array(glist[p])).dot(psiold)) == (top.iloc[o]['state'])):
                            toparray.append((array(glist[p])).dot(psiold))
                            actarray.append(p)
        
                garray =[] #create an array of all possible new states and a corresponding array with associated actions
                actg = []
                for a in range(0,len(top)):
                    for b in range(0,len(glist)):
                        if (str((array(glist[b])).dot(psiold)) == (gather.iloc[a]['state'])):
                            garray.append((array(glist[b])).dot(psiold))
                            actg.append(b)
        
                q = randrange(100)
                if q > 70: #Create a percentage chance that the next state will be one with a max Q value (expoitation) or a state obtained from a random action (exploration)
                    r = randrange(len(toparray))
                    psiold = toparray[r]
                    action = actarray[r]
                else:
                    r = randrange(len(garray))
                    psiold = garray[r]
                    action = actg[r]
        
            #print(str(t) + 'th state is ' + str(psiold) + ' after action ' + str(action))
        #print(repeats) 
    tots1 = tots1.append(table) #add the updated Q values from this agent to a table
    oppa = table.loc[(table.state == str(psinit))] #select the rows with the initial state
    lol = oppa.sort_values("Q", ascending=False) #sort according to Q value
    top = lol.head(1) #Choose the state action pair with the top Q value
    for n in [0, 1, 2, 3, 4, 5, 6, 7, 8]:
        
        oppa1 = table.loc[(table.state == top['new'].values[n])] #Find the state that results from the top action being applied
        lol = oppa1.sort_values("Q", ascending=False) #find the max Q value of next state
        top1 = lol.head(1)
        
        top = top.append(top1) #add it to the dataframe of steps
        #print(top1)
         
    final = final.append(top) #add this agents top first 4 steps to the other agents top first 4 steps
    final = final.reset_index(drop=True)

0 has begun
goal reached
goal reached
goal reached
goal reached
goal reached
goal reached
goal reached
goal reached


In [130]:
reads = final.head(30)
reads

state  gate  \
0        [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]     4   
1  [[0.70710678+0.j]\n [0.70710678+0.j]\n [0.    ...     8   
2  [[0.70710678+0.j        ]\n [0.        +0.7071...     8   
3  [[ 0.70710678+0.j]\n [-0.70710678+0.j]\n [ 0. ...     4   
4        [[0.+0.j]\n [1.+0.j]\n [0.+0.j]\n [0.+0.j]]     2   
5        [[0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [1.+0.j]]     1   
6        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]     8   
7        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]     8   
8        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]     8   
9        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]     8   

                                                 new  fidelity          Q  
0  [[0.70710678+0.j]\n [0.70710678+0.j]\n [0.    ...       0.0  19.909307  
1  [[0.70710678+0.j        ]\n [0.        +0.7071...       0.0  21.887838  
2  [[ 0.70710678+0.j]\n [-0.70710678+0.j]\n [ 0. ...       0.0  25.320677  
3        [[0.+0.j]\n [1.+0.j]\n [0.+0.j]\n [0.+0.j]]       0.0  29.135590  
4        [[0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [1.+0.j]]       0.0  33.195768  
5        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]       0.0  37.927792  
6        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]       1.0  42.924906  
7        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]       1.0  42.924906  
8        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]       1.0  42.924906  
9        [[0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]       1.0  42.924906

In [131]:
together = tots1.groupby(['state','gate','new', 'fidelity'])['Q'].mean().reset_index()

In [132]:
ask = zeroone
table = together.copy()
final = pd.DataFrame() #Dataframe to store state action pairs for top Q values for each agent
tots1 = pd.DataFrame() 
oppa = table.loc[(table.state == str(ask))] #select the rows with the initial state
lol = oppa.sort_values("Q", ascending=False) #sort according to Q value
top = lol.head(1) #Choose the state action pair with the top Q value
for n in [0, 1, 2, 3, 4, 5, 6, 7, 8]:
        
    oppa1 = table.loc[(table.state == top['new'].values[n])] #Find the state that results from the top action being applied
    lol = oppa1.sort_values("Q", ascending=False) #find the max Q value of next state
    top1 = lol.head(1)
        
    top = top.append(top1) #add it to the dataframe of steps
    if (top.iloc[(n+1)]['gate'] == top.iloc[(n)]['gate']):
        break
         
final = final.append(top) #add this agents top first 4 steps to the other agents top first 4 steps
final = final.reset_index(drop=True)

reads = final.head(30)

first = reads.iloc[0]['state']
last = reads.iloc[(len(reads) -1)]['new']
print('to get from ')
print(first)
print(' to ')
print(last)
print(' use actions: ')
for ii in range(0,len(reads)):
    act = reads.iloc[ii]['gate']
    act2 = glist[act]
    print(str(act) + str(act2))

to get from 
[[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]
 to 
[[0.+0.j]
 [0.+0.j]
 [1.+0.j]
 [0.+0.j]]
 use actions: 
2[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
1[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
8[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]
8[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]


In [133]:
glist[8].dot(glist[1].dot(glist[2].dot(zeroone)))

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j]])