In [1]:
from numpy import *
import cmath
from random import randrange
import pandas as pd
import time
from IPython.display import clear_output
import scipy
import matplotlib.pyplot as plt

In [2]:
one = array([[int(0) + 0j], [int(1) + 0j]])
zero = array([[int(1) + 0j], [int(0) + 0j]])
plus = (1/sqrt(2))*(zero + one)
minus = (1/sqrt(2))*(zero - one)

In [3]:
def norm(state):
    prod = scipy.sqrt(transpose(state.conjugate()).dot(state))
    return(asscalar(prod))

In [4]:
def fidelityp(guess, right):
    mult = (transpose(guess.conjugate())).dot(right)*(transpose(right.conjugate())).dot(guess)
    #print(mult)
    root = asscalar((mult))
    return(abs(root))

In [5]:
H = (1/sqrt(2))*array([[1,1],[1, -1]])
I = array([[1 , 0], [0, 1]])
T = array([[1, 0], [0, exp((1j*pi)/4)]])
S = array([[1, 0], [0, 1j]])

In [6]:
X = array([[0 , 1], [1,0]])
X1 = kron(kron(X, I),I)
X2 = kron(kron(I,X),I)
X3 = kron(kron(I,I),X)

Y = array([[0 , -1j], [1j,0]])
Y1 = kron(kron(Y, I),I)
Y2 = kron(kron(I,Y),I)
Y3 = kron(kron(I,I),Y)

Z = array([[1 , 0], [0,-1]])
Z1 = kron(kron(Z, I),I)
Z2 = kron(kron(I,Z),I)
Z3 = kron(kron(I,I),Z)

In [7]:
zerop = zero*transpose(zero)
onep = one*transpose(one)


In [8]:
CNOT13 = kron(kron(zerop,I),I) + kron(kron(onep,I),X)
CNOT31 = kron(kron(I,I),zerop) + kron(kron(X,I),onep)
CNOT21 = kron(kron(I,zerop),I) + kron(kron(X,onep),I)
CNOT23 = kron(kron(I,zerop),I) + kron(kron(I,onep),X)
CNOT32 = kron(kron(I,I),zerop) + kron(kron(I,X),onep)
CNOT12 = kron(kron(zerop,I),I) + kron(kron(onep,X),I)
H1 = kron(kron(H, I), I)
H2 = kron(kron(I, H), I)
H3 = kron(kron(I, I), H)
T1 = kron(kron(T, I), I)
T2 = kron(kron(I, T), I)
T3 = kron(kron(I, I), T)
S1 = kron(kron(S, I), I)
S2 = kron(kron(I, S), I)
S3 = kron(kron(I, I), S)
I3 = kron(kron(I,I),I)


In [9]:
glist = [I3, CNOT12, CNOT21, CNOT13, CNOT31, CNOT23, CNOT32, H1, H2, H3, T1, T2, T3, S1, S2, S3]

In [10]:
zero3 = kron(kron(zero,zero),zero)
zzo = kron(kron(zero,zero),one)
zoz = kron(kron(zero,one),zero)
zoo = kron(kron(zero,one),one)
ozz = kron(kron(one,zero),zero)
ozo = kron(kron(one,zero),one)
ooz = kron(kron(one,one),zero)
one3 = kron(kron(one,one),one)


In [11]:
Q_table = pd.DataFrame()
for m in range(0,len(glist)):
    gate = m
    new = (glist[m].dot(zero3))
    Q = pd.DataFrame({'state' : str(zero3), 'gate':gate, 'new': str(new), 'Q':0, 'fidelity':0}, index=[0])
    Q_table = Q_table.append(Q)
Q_table = Q_table.reset_index(drop=True)

In [12]:
Q_table

state  gate  \
0   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     0   
1   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     1   
2   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     2   
3   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     3   
4   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     4   
5   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     5   
6   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     6   
7   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     7   
8   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     8   
9   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...     9   
10  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...    10   
11  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...    11   
12  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...    12   
13  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...    13   
14  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...    14   
15  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...    15   

                                                  new  Q  fidelity  
0   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
1   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
2   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
3   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
4   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
5   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
6   [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
7   [[0.70710678+0.j]\n [0.        +0.j]\n [0.    ...  0         0  
8   [[0.70710678+0.j]\n [0.        +0.j]\n [0.7071...  0         0  
9   [[0.70710678+0.j]\n [0.70710678+0.j]\n [0.    ...  0         0  
10  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
11  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
12  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
13  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
14  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0  
15  [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [...  0         0

In [151]:
alpha = 0.5 #how much we update Q for every new action
gamma = 0.9 #discount factor 

num_iter = 1 #how many agents will come up with their own Q values from scratch
num_repeats = 100 #How many events one agent will go through to obtain Q values
penalty = 1 #How much taken off reward for each step
steps = 10 #How many steps in an event

In [15]:
right = Z1.dot(H3.dot(X2.dot(X1.dot(zero3))))
right

array([[ 0.        +0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [-0.70710678+0.j],
       [-0.70710678+0.j]])

In [15]:
right = X2.dot((X1.dot(ozz)))
right

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [50]:
H1.dot(S1.dot(S1.dot(H1.dot(one3))))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [83]:
save = together.copy()

In [152]:
final = pd.DataFrame() #Dataframe to store state action pairs for top Q values for each agent
tots1 = pd.DataFrame() #Dataframe to store all Q values of all agents 
for iter in range(0,num_iter): #Begin an agent
    table = save.copy() #set the starting dataframe (empty Q values or precalculated)
    print(str(iter) + ' has begun')
    for repeats in range(0,num_repeats):
        psinit = one3.copy()
        psiold = psinit.copy() #save the current state
        reward = 0 #Reset the reward
        for t in range(0,steps): #begin a step
            reward += penalty #add more penalty with each step
        
            sec = table[table['state']==str(psiold)] #choose rows of the original table that contain the current state
            
            if len(sec) == 0: #if the new state is not in the dataframe, insert it with all the possible actions
                for s in range(0,len(glist)):
                    lad = glist[s].dot(psiold)
                    sec = pd.DataFrame({'state' : str(psiold), 'gate':s, 'new':str(lad), 'Q':0, 'fidelity':0}, index=[0])
                    table = table.append(sec)
        
            gather = pd.DataFrame() #dataframe to collect all possible new states 
            for n in range(0,(len(sec))): #iterate through the rows that contain the current state
                for z in range(0,len(glist)): # find the action associated with the state in each row
                    if(sec.iloc[n]['gate']== z):
                        apply = array(glist[z])
                        zed = z
                    
                psinew = apply.dot(psiold) #create new state by applying action
                
                
                news = table[table['state']==str(psinew)] #choose part of dataframe that contains the new state
            
                if len(news) == 0: #if the new state is not in the dataframe, insert it with all the possible actions
                    for s in range(0,len(glist)):
                        lad = glist[s].dot(psinew)
                        news = pd.DataFrame({'state' : str(psinew), 'gate':s, 'new':str(lad), 'Q':0, 'fidelity':0}, index=[0])
                        table = table.append(news)
                    
                maxQ = max(news['Q']) #find the max Q value the new state
                gather = gather.append(news).drop_duplicates() #create a dataframe of all possible new states
                plus = 0 #reset award
                if (fidelityp(psiold, right)) > 0.99999999999:
                     plus = 5
                elif (fidelityp(psiold, right)) > 0.85:
                     plus = (fidelityp(psiold, right))*(4/(0.15)) + (1 - (fidelityp(psiold, right))*(4/(0.15)))
                else:
                    plus = 0    
                table.loc[(table.state == str(psiold)) & (table.gate == zed), 'Q'] += alpha*((plus - reward) + gamma*(maxQ) - sec.iloc[n]['Q'])
                table.loc[(table.state == str(psiold)) & (table.gate == zed), 'fidelity'] = (fidelityp(psiold, right))
                #update the Q value of the old state based on the rewards given by the new state
            if plus == 5: #If we have reached the state we want we can stop
                print('goal reached')
                break
            else:
                top = gather.loc[(gather.Q == max(gather['Q']))] #collect the max Q value from all possible new states
                maxi = top.iloc[0]['Q']
                q = randrange(100)
                if (q > 60) and (maxi != 0): #Create a percentage chance that the next state will be one with a max Q value (expoitation) or a state obtained from a random action (exploration)
                    toparray =[] #sort these into an array with their associated action
                    actarray =[]
                    for o in range(0,len(top)):
                        for p in range(0,len(glist)):
                            if (str((array(glist[p])).dot(psiold)) == (top.iloc[o]['state'])):
                                toparray.append((array(glist[p])).dot(psiold))
                                actarray.append(p)
                    r = randrange(len(toparray))
                    psiold = toparray[r]
                    action = actarray[r]
                    
                else:
                    garray =[] #create an array of all possible new states and a corresponding array with associated actions
                    actg = []
                    for a in range(0,len(sec)):
                        b = sec.iloc[a]['gate']
                        actg.append(b)
                        garray.append((array(glist[b])).dot(psiold))
                    r = randrange(len(garray))
                    psiold = garray[r]
                    action = actg[r]
                    
        
            #print(str(t) + 'th state is ' + str(psiold) + ' after action ' + str(action))
        print(repeats) 
    tots1 = tots1.append(table) #add the updated Q values from this agent to a table
    oppa = table.loc[(table.state == str(psinit))] #select the rows with the initial state
    lol = oppa.sort_values("Q", ascending=False) #sort according to Q value
    top = lol.head(1) #Choose the state action pair with the top Q value
    for n in [0, 1, 2, 3, 4, 5, 6, 7, 8]:
        
        oppa1 = table.loc[(table.state == top['new'].values[n])] #Find the state that results from the top action being applied
        lol = oppa1.sort_values("Q", ascending=False) #find the max Q value of next state
        top1 = lol.head(1)
        
        top = top.append(top1) #add it to the dataframe of steps
        #print(top1)
         
    final = final.append(top) #add this agents top first 4 steps to the other agents top first 4 steps
    final = final.reset_index(drop=True)

0 has begun
0
1
goal reached
2
goal reached
3
goal reached
4
5
6
7
8
goal reached
9
10
11
12
goal reached
13
14
15
goal reached
16
goal reached
17
18
19
goal reached
20
goal reached
21
goal reached
22
goal reached
23
24
goal reached
25
goal reached
26
goal reached
27
28
goal reached
29
30
31
goal reached
32
33
34
goal reached
35
36
goal reached
37
38
39
goal reached
40
41
42
43
goal reached
44
goal reached
45
goal reached
46
47
48
goal reached
49
50
51
52
goal reached
53
54
goal reached
55
56
57
goal reached
58
59
60
61
goal reached
62
goal reached
63
64
65
66
67
68
69
goal reached
70
goal reached
71
goal reached
72
goal reached
73
74
goal reached
75
goal reached
76
goal reached
77
78
goal reached
79
goal reached
80
81
82
83
84
goal reached
85
goal reached
86
goal reached
87
goal reached
88
89
goal reached
90
goal reached
91
92
goal reached
93
94
95
96
goal reached
97
goal reached
98
goal reached
99


In [141]:
pd.set_option('display.max_colwidth', 100)
reads = final.head(30)
reads

Q  fidelity  gate  \
0  32.880871       0.5     9   
1  37.521955       1.0     5   
2  37.521955       1.0     5   
3  37.521955       1.0     5   
4  37.521955       1.0     5   
5  37.521955       1.0     5   
6  37.521955       1.0     5   
7  37.521955       1.0     5   
8  37.521955       1.0     5   
9  37.521955       1.0     5   

                                                                                                   new  \
0  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
1  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
2  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
3  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
4  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
5  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
6  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
7  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
8  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   
9  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...   

                                                                                                 state  
0              [[0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [1.+0.j]\n [0.+0.j]]  
1  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
2  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
3  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
4  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
5  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
6  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
7  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
8  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...  
9  [[0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n ...

In [153]:
together = tots1.groupby(['state','gate','new', 'fidelity'])['Q'].mean().reset_index()

In [155]:
ask = zero3
table = together.copy()
final = pd.DataFrame() #Dataframe to store state action pairs for top Q values for each agent
tots1 = pd.DataFrame() 
oppa = table.loc[(table.state == str(ask))] #select the rows with the initial state
lol = oppa.sort_values("Q", ascending=False) #sort according to Q value
top = lol.head(1) #Choose the state action pair with the top Q value
for n in [0, 1, 2, 3, 4, 5, 6, 7, 8]:
        
    oppa1 = table.loc[(table.state == top['new'].values[n])] #Find the state that results from the top action being applied
    lol = oppa1.sort_values("Q", ascending=False) #find the max Q value of next state
    top1 = lol.head(1)
        
    top = top.append(top1) #add it to the dataframe of steps
    #if (top.iloc[(n+1)]['new'] == top.iloc[(n+1)]['state']):
        #break
        
top = top.reset_index(drop=True)

reads = top.head(30)

first = reads.iloc[0]['state']
last = reads.iloc[(len(reads) -1)]['state']
print('to get from ')
print(first)
print(' to ')
print(last)
print(' use actions: ')
for ii in range(0,len(reads)):
    act = reads.iloc[ii]['gate']
    print(str(act))
reads

to get from 
[[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]
 to 
[[ 0.5+0.j]
 [ 0.5+0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [-0.5+0.j]
 [-0.5+0.j]
 [ 0. +0.j]
 [ 0. +0.j]]
 use actions: 
7
13
13
9
0
0
0
0
0
0


state  \
0              [[1.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]\n [0.+0.j]]   
1  [[0.70710678+0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.70710678+0.j]\n ...   
2  [[0.70710678+0.j        ]\n [0.        +0.j        ]\n [0.        +0.j        ]\n [0.        +0....   
3  [[ 0.70710678+0.j]\n [ 0.        +0.j]\n [ 0.        +0.j]\n [ 0.        +0.j]\n [-0.70710678+0....   
4  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
5  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
6  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
7  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
8  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
9  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   

   gate  \
0     7   
1    13   
2    13   
3     9   
4     0   
5     0   
6     0   
7     0   
8     0   
9     0   

                                                                                                   new  \
0  [[0.70710678+0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.        +0.j]\n [0.70710678+0.j]\n ...   
1  [[0.70710678+0.j        ]\n [0.        +0.j        ]\n [0.        +0.j        ]\n [0.        +0....   
2  [[ 0.70710678+0.j]\n [ 0.        +0.j]\n [ 0.        +0.j]\n [ 0.        +0.j]\n [-0.70710678+0....   
3  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
4  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
5  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
6  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
7  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
8  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   
9  [[ 0.5+0.j]\n [ 0.5+0.j]\n [ 0. +0.j]\n [ 0. +0.j]\n [-0.5+0.j]\n [-0.5+0.j]\n [ 0. +0.j]\n [ 0....   

   fidelity          Q  
0       0.0  21.005524  
1       0.0  23.404289  
2       0.0  26.508435  
3       0.0  24.372129  
4       0.0  26.026400  
5       0.0  26.026400  
6       0.0  26.026400  
7       0.0  26.026400  
8       0.0  26.026400  
9       0.0  26.026400

In [59]:
glist[9].dot(glist[3].dot(glist[1].dot(glist[4].dot(zzo))))

array([[0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.70710678+0.j]])