Import first

In [58]:
from numpy import *
import cmath
from random import randrange

Set variables

In [59]:
theta = pi/4
phi = 0
a = cos(theta)
#b = exp(1j*phi)*sin(theta)
b = sin(theta)

In [60]:
one = array([[int(0) + 0j], [int(1) +0j]])
zero = array([[int(1) + 0j], [int(0) + 0j]])
psi = a*zero + b*one

In [61]:
psi

array([[0.70710678+0.j],
       [0.70710678+0.j]])

Define matrices

In [62]:
X = array([[0 , 1], [1, 0]])
Iden = array([[1 , 0], [0, 1]])
Z = array([[1,0],[0, -1]])
CNOT = array([[1 , 0 , 0 , 0], [0 , 1 , 0 , 0], [0 , 0 , 0 , 1], [0 , 0 , 1 , 0]])

Tensor Produucts (bit flips)

In [63]:
H = (1/sqrt(2))*array([[1,1],[1, -1]])
I = array([[1 , 0], [0, 1]])
T = array([[1, 0], [0, exp((1j*pi)/4)]])
S = array([[1, 0], [0, 1j]])

In [64]:
X = array([[0 , 1], [1,0]])
X1 = kron(kron(X, I),I)
X2 = kron(kron(I,X),I)
X3 = kron(kron(I,I),X)

Y = array([[0 , -1j], [1j,0]])
Y1 = kron(kron(Y, I),I)
Y2 = kron(kron(I,Y),I)
Y3 = kron(kron(I,I),Y)

Z = array([[1 , 0], [0,-1]])
Z1 = kron(kron(Z, I),I)
Z2 = kron(kron(I,Z),I)
Z3 = kron(kron(I,I),Z)

In [65]:
zerop = zero*transpose(zero)
onep = one*transpose(one)

In [77]:
Z12 = kron(kron(Z, Z), Iden)
Z23 = kron(kron(Iden, Z), Z)

In [66]:
CNOT13 = kron(kron(zerop,I),I) + kron(kron(onep,I),X)
CNOT31 = kron(kron(I,I),zerop) + kron(kron(X,I),onep)
CNOT21 = kron(kron(I,zerop),I) + kron(kron(X,onep),I)
CNOT23 = kron(kron(I,zerop),I) + kron(kron(I,onep),X)
CNOT32 = kron(kron(I,I),zerop) + kron(kron(I,X),onep)
CNOT12 = kron(kron(zerop,I),I) + kron(kron(onep,X),I)
H1 = kron(kron(H, I), I)
H2 = kron(kron(I, H), I)
H3 = kron(kron(I, I), H)
T1 = kron(kron(T, I), I)
T2 = kron(kron(I, T), I)
T3 = kron(kron(I, I), T)
S1 = kron(kron(S, I), I)
S2 = kron(kron(I, S), I)
S3 = kron(kron(I, I), S)
I3 = kron(kron(I,I),I)

Encoding

In [149]:
psi3 = kron((kron(psi,zero)), zero)
psi3

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

Applying other gates

In [69]:
test = 
test

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [111]:
H1.dot(test)

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

In [140]:
psix = CNOT13.dot(CNOT12.dot(psi3))
psix

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j]])

In [18]:
psip = kron((kron(one,one)),one) + kron((kron(zero,zero)),zero)
psip

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

Random bit flips

In [155]:
k = randrange(4)
print(k)

2


In [156]:
psie = psi3

if k == 0:
    psir = X1.dot(psie)
elif k == 1:
    psir = X2.dot(psie)
elif k == 2:
    psir = X3.dot(psie)
elif k == 3:
    psir = psie

In [157]:
psir

array([[0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j]])

In [131]:
i = transpose(psir).dot(Z12.dot(psir))
int(i[0][0].real)

0

0

In [162]:
Z23.dot(psir)

array([[ 0.        +0.j],
       [-0.70710678+0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [ 0.        +0.j],
       [-0.70710678+0.j],
       [ 0.        +0.j],
       [ 0.        +0.j]])

Syndrome

In [160]:
o = (transpose(psir)).dot(Z23.dot(psir))
int((o[0][0]).real)

-1

In [158]:
o = (transpose(Z12.dot(psir))).dot(psir)
if int((o[0][0]).real)==1:
    val1 = 0
elif int((o[0][0]).real)== -1:
    val1 = 1
else:
    print('error')
    val1 = int((o[0][0]).real)

val1

error


0

In [159]:
p = (transpose(Z23.dot(psir))).dot(psir)
if int((p[0][0]).real)==1:
    val2 = 0
elif int((p[0][0]).real)== -1:
    val2 = 1
else:
    print('error')
    val2 = int((p[0][0]).real)
val2

1

In [148]:
if (val1 == 0) & (val2 == 0):
    print("No error")
    err = 0
elif (val1 == 0) & (val2 == 1):
    print("Qubit 3 has flipped")
    err = 3
elif (val1 == 1) & (val2 == 1):
    print("Qubit 2 has flipped")
    err = 2
elif (val1 == 1) & (val2 == 0):
    print("Qubit 1 has flipped")
    err = 1

Qubit 3 has flipped


Correction

In [123]:
if err == 1:
    psif = (X1.dot(psir))
elif err == 2:
    psif = X2.dot(psir)
elif err == 3:
    psif = (X3.dot(psir))
elif err == 0:
    psif = psir

In [124]:
psif

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

Decoding

In [54]:
CNOT13.dot(CNOT12.dot(psix))

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

In [125]:
H1.dot(psif)

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [163]:
psir

array([[0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j]])